fileVersion: 1
id: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
name: GOVCONFIG
operation:
  database: ""
  deployEnabled: true
  description: ""
  locationName: SRC_GOVERN
  metadata:
    columns:
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 196e6f6d-aca4-471c-83b8-788dcad68115
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: ""
        name: CONFIGID
        nullable: false
        primaryKey: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 42490121-1afd-4eb6-b27e-a1f3538cb0b4
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: ""
        name: CONFIGTYPEID
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 8c9162b9-4fa5-4980-a830-3a921dd7a31f
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: VARCHAR(1000)
        defaultValue: ""
        description: ""
        name: NAME
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 09c31a55-86d6-422e-a057-d95d8f5ed82f
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: VALUE
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 7fb3de3b-dddd-4556-bf76-4b4eeaedc2e8
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: VARCHAR(16777216)
        defaultValue: ""
        description: ""
        name: DESCRIPTION
        nullable: true
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 42752761-9152-48c4-892a-c87c9a85bd94
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: VARCHAR(40)
        defaultValue: ""
        description: ""
        name: CREATED_BY
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: fa8f6c44-30c2-4ff3-a153-7b80e6f3e86f
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: TIMESTAMP_NTZ(0)
        defaultValue: ""
        description: ""
        name: HVR_CAPTURE_TIME
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 52e75244-ac46-4206-8f15-08281c5750fd
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: NUMBER(38,0)
        defaultValue: ""
        description: ""
        name: HVR_CHANGE_OP
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: c189d6f1-68e8-42ff-8814-9e7a3723e7ab
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: VARCHAR(46)
        defaultValue: ""
        description: ""
        name: HVR_CHANGE_SEQUENCE
        nullable: false
        primaryKey: true
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 12e01fc4-116f-4534-9e78-349dab6e69da
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: TIMESTAMP_TZ(3)
        defaultValue: ""
        description: ""
        name: HVR_CHANGE_TIME
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
      - acceptedValues:
          strictMatch: true
          values: []
        appliedColumnTests: {}
        columnReference:
          columnCounter: 05992e2a-da03-4523-9c67-dea482ec1eba
          stepCounter: ff4e0401-6d28-41ef-bcde-e5c10ea4c9a9
        config: {}
        dataType: VARCHAR(30)
        defaultValue: ""
        description: ""
        name: SOURCE_CD
        nullable: false
        primaryKey: false
        sourceColumnReferences:
          - columnReferences: []
            transform: ""
        transform: ""
        uniqueKey: false
  name: GOVCONFIG
  schema: ""
  sqlType: Source
  type: sourceInput
  version: 1
type: Node
